name: GoldenGlow
author: [RyanV97, JeanMarc]
description: The plugin with Obscure Obsidian's server code!
main: com.goldenglowspigot.GoldenGlow
version: 1.0
api-version: 1.12.2
commands:
  channel:
    description: used for chat channels
    usage: /channel <list/ChannelName> <Username>
  global:
    description: used to switch to/talk in the global channel
    usage: /global [Message]
  staff:
    description: used to switch to/talk in the staff channel
    usage: /staff [Message]