name: GoldenGlow
author: [RyanV97, JeanMarc]
description: The plugin with Obscure Obsidian's server code!
main: com.goldenglowspigot.GoldenGlow
version: 1.0
api-version: 1.12.2
commands:
  channel:
    description: used for chat channels
    usage: /channel <list/ChannelName> <Username>